name: Deploy

on:
  push:
    branches:
      - main

jobs:
  vercel-deploy:
    name: Vercel Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: |
          npm install --global vercel@latest

      - name: Deploy
        run: |
          vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
